name: adomob
description: Application mobile Adomelec
publish_to: 'none'
version: 0.1.0
repository: https://github.com/mbenfe/adomob.git

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  animator: ^3.1.0
  build_runner: ^2.3.3
  dartdoc: ^6.2.2
  dhttpd: ^4.0.1
  flutter:
    sdk: flutter
  flutter_circular_text: ^0.3.1
  flutter_form_builder: ^7.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.3.6
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  material_design_icons_flutter: ^6.0.7096
  mqtt_client: ^9.8.1
  sleek_circular_slider: ^2.0.1
  syncfusion_flutter_charts: ^21.2.4
  syncfusion_flutter_core: ^21.2.6
  syncfusion_flutter_gauges: ^21.1.41
  toggle_switch: ^2.1.0
  weather: ^2.0.1
  weather_icons: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - images/dark_theme_gauge.png
    - images/dark_theme_gauge_wip.png
    - images/temperature_gauge.png
    - images/humidity_gauge.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/AppIcon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#ed1e79"
