name: my_adomob
description: A new Flutter package project.
version: 0.0.1
homepage:
Repository: https://github.com/mbenfe/my_adomob.git
publish_to: 'none'

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.0.0" 

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ">=1.0.3"
  json_annotation: ^4.8.0
  mqtt_client: ^9.8.1
  my_widgets:
    path: ../my_widgets
  my_mqtt:
    path: ../my_mqtt
  my_models:
    path: ../my_models
  dart_code_metrics: ^5.7.2
  freezed: ^2.3.2
  material_design_icons_flutter: ^6.0.7096
  dartdoc: ^6.2.2
  dhttpd: ^4.0.1
json_annotation: ^4.4.0
json_serializable: ^6.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  dependency_validator: ^3.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
 # assets:
 # - assets/layout.json

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
