import 'package:weather_icons/weather_icons.dart';

Map<String, dynamic> tabIcons = {
  "200": {"label": "thunderstorm with light rain", "icon": const BoxedIcon(WeatherIcons.storm_showers)},
  "201": {"label": "thunderstorm with rain", "icon": const BoxedIcon(WeatherIcons.storm_showers)},
  "202": {"label": "thunderstorm with heavy rain", "icon": const BoxedIcon(WeatherIcons.storm_showers)},
  "210": {"label": "light thunderstorm", "icon": const BoxedIcon(WeatherIcons.storm_showers)},
  "211": {"label": "thunderstorm", "icon": const BoxedIcon(WeatherIcons.day_cloudy_gusts)},
  "212": {"label": "heavy thunderstorm", "icon": const BoxedIcon(WeatherIcons.day_cloudy_gusts)},
  "221": {"label": "ragged thunderstorm", "icon": const BoxedIcon(WeatherIcons.day_cloudy_gusts)},
  "230": {"label": "thunderstorm with light drizzle", "icon": const BoxedIcon(WeatherIcons.storm_showers)},
  "231": {"label": "thunderstorm with drizzle", "icon": const BoxedIcon(WeatherIcons.storm_showers)},
  "232": {"label": "thunderstorm with heavy drizzle", "icon": const BoxedIcon(WeatherIcons.storm_showers)},
  "300": {"label": "light intensity drizzle", "icon": const BoxedIcon(WeatherIcons.sprinkle)},
  "301": {"label": "drizzle", "icon": const BoxedIcon(WeatherIcons.sprinkle)},
  "302": {"label": "heavy intensity drizzle", "icon": const BoxedIcon(WeatherIcons.sprinkle)},
  "310": {"label": "light intensity drizzle rain", "icon": const BoxedIcon(WeatherIcons.sprinkle)},
  "311": {"label": "drizzle rain", "icon": const BoxedIcon(WeatherIcons.sprinkle)},
  "312": {"label": "heavy intensity drizzle rain", "icon": const BoxedIcon(WeatherIcons.sprinkle)},
  "313": {"label": "shower rain and drizzle", "icon": const BoxedIcon(WeatherIcons.sprinkle)},
  "314": {"label": "heavy shower rain and drizzle", "icon": const BoxedIcon(WeatherIcons.sprinkle)},
  "321": {"label": "shower drizzle", "icon": const BoxedIcon(WeatherIcons.sprinkle)},
  "500": {"label": "light rain", "icon": const BoxedIcon(WeatherIcons.rain)},
  "501": {"label": "moderate rain", "icon": const BoxedIcon(WeatherIcons.rain)},
  "502": {"label": "heavy intensity rain", "icon": const BoxedIcon(WeatherIcons.rain)},
  "503": {"label": "very heavy rain", "icon": const BoxedIcon(WeatherIcons.rain)},
  "504": {"label": "extreme rain", "icon": const BoxedIcon(WeatherIcons.rain)},
  "511": {"label": "freezing rain", "icon": const BoxedIcon(WeatherIcons.rain_mix)},
  "520": {"label": "light intensity shower rain", "icon": const BoxedIcon(WeatherIcons.showers)},
  "521": {"label": "shower rain", "icon": const BoxedIcon(WeatherIcons.showers)},
  "522": {"label": "heavy intensity shower rain", "icon": const BoxedIcon(WeatherIcons.showers)},
  "531": {"label": "ragged shower rain", "icon": const BoxedIcon(WeatherIcons.showers)},
  "600": {"label": "light snow", "icon": const BoxedIcon(WeatherIcons.snow)},
  "601": {"label": "snow", "icon": const BoxedIcon(WeatherIcons.snow)},
  "602": {"label": "heavy snow", "icon": const BoxedIcon(WeatherIcons.snow)},
  "611": {"label": "sleet", "icon": const BoxedIcon(WeatherIcons.day_sleet)},
  "612": {"label": "shower sleet", "icon": const BoxedIcon(WeatherIcons.day_sleet)},
  "615": {"label": "light rain and snow", "icon": const BoxedIcon(WeatherIcons.rain_mix)},
  "616": {"label": "rain and snow", "icon": const BoxedIcon(WeatherIcons.rain_mix)},
  "620": {"label": "light shower snow", "icon": const BoxedIcon(WeatherIcons.rain_mix)},
  "621": {"label": "shower snow", "icon": const BoxedIcon(WeatherIcons.rain_mix)},
  "622": {"label": "heavy shower snow", "icon": const BoxedIcon(WeatherIcons.rain_mix)},
  "701": {"label": "mist", "icon": const BoxedIcon(WeatherIcons.sprinkle)},
  "711": {"label": "smoke", "icon": const BoxedIcon(WeatherIcons.smoke)},
  "721": {"label": "haze", "icon": const BoxedIcon(WeatherIcons.day_haze)},
  "731": {"label": "sand, dust whirls", "icon": const BoxedIcon(WeatherIcons.day_cloudy_gusts)},
  "741": {"label": "fog", "icon": const BoxedIcon(WeatherIcons.fog)},
  "751": {"label": "sand", "icon": const BoxedIcon(WeatherIcons.day_cloudy_gusts)},
  "761": {"label": "dust", "icon": const BoxedIcon(WeatherIcons.dust)},
  "762": {"label": "volcanic ash", "icon": const BoxedIcon(WeatherIcons.smog)},
  "771": {"label": "squalls", "icon": const BoxedIcon(WeatherIcons.day_windy)},
  "781": {"label": "tornado", "icon": const BoxedIcon(WeatherIcons.tornado)},
  "800": {"label": "clear sky", "icon": const BoxedIcon(WeatherIcons.day_sunny)},
  "801": {"label": "few clouds", "icon": const BoxedIcon(WeatherIcons.day_cloudy)},
  "802": {"label": "scattered clouds", "icon": const BoxedIcon(WeatherIcons.day_cloudy)},
  "803": {"label": "broken clouds", "icon": const BoxedIcon(WeatherIcons.day_cloudy)},
  "804": {"label": "overcast clouds", "icon": const BoxedIcon(WeatherIcons.day_cloudy)},
  "900": {"label": "tornado", "icon": const BoxedIcon(WeatherIcons.tornado)},
  "901": {"label": "tropical storm", "icon": const BoxedIcon(WeatherIcons.hurricane)},
  "902": {"label": "hurricane", "icon": const BoxedIcon(WeatherIcons.hurricane)},
  "903": {"label": "cold", "icon": const BoxedIcon(WeatherIcons.snowflake_cold)},
  "904": {"label": "hot", "icon": const BoxedIcon(WeatherIcons.hot)},
  "905": {"label": "windy", "icon": const BoxedIcon(WeatherIcons.day_windy)},
  "906": {"label": "hail", "icon": const BoxedIcon(WeatherIcons.day_hail)},
  "951": {"label": "calm", "icon": const BoxedIcon(WeatherIcons.day_sunny)},
  "952": {"label": "light breeze", "icon": const BoxedIcon(WeatherIcons.day_cloudy_gusts)},
  "953": {"label": "gentle breeze", "icon": const BoxedIcon(WeatherIcons.day_cloudy_gusts)},
  "954": {"label": "moderate breeze", "icon": const BoxedIcon(WeatherIcons.day_cloudy_gusts)},
  "955": {"label": "fresh breeze", "icon": const BoxedIcon(WeatherIcons.day_cloudy_gusts)},
  "956": {"label": "strong breeze", "icon": const BoxedIcon(WeatherIcons.day_cloudy_gusts)},
  "957": {"label": "high wind, near gale", "icon": const BoxedIcon(WeatherIcons.day_cloudy_gusts)},
  "958": {"label": "gale", "icon": const BoxedIcon(WeatherIcons.day_cloudy_gusts)},
  "959": {"label": "severe gale", "icon": const BoxedIcon(WeatherIcons.day_cloudy_gusts)},
  "960": {"label": "storm", "icon": const BoxedIcon(WeatherIcons.day_cloudy_gusts)},
  "961": {"label": "violent storm", "icon": const BoxedIcon(WeatherIcons.day_cloudy_gusts)},
  "962": {"label": "hurricane", "icon": const BoxedIcon(WeatherIcons.day_cloudy_gusts)}
};
